name: 'Docker Package Versions'
description: 'A GitHub Action to capture and list installed packages and their versions in a Docker image.'
author: 'DockForge <dockforge@gmail.com>'
inputs:
  image:
    description: "The Docker image to scan"
    required: true
  github_token:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install syft
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan Docker image with syft
      shell: bash
      run: |
        syft ${{ inputs.image }} -o json > /workspace/packages.json

    - name: Commit and push changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        cd $GITHUB_WORKSPACE
        mv /workspace/packages.json packages.json
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add packages.json
        git commit -m "Add package versions report"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD:${{ github.ref }}