name: 'Docker Package Versions'
description: 'A GitHub Action to capture and list installed packages and their versions in a Docker image.'
author: 'DockForge <dockforge@gmail.com>'
inputs:
  image:
    description: "The Docker image to scan"
    required: true
  github_token:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script inside the target Docker image
      shell: bash
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace ${{ inputs.image }} /bin/bash /workspace/src/entrypoint.sh

    - name: Commit and push changes
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add package_versions.txt
        git commit -m "Add package versions report"
        git push https://${{ inputs.github_token }}@github.com/${{ github.repository }}.git
