name: 'Docker Package Versions'
description: 'A GitHub Action to capture and list installed packages and their versions in a Docker image.'
author: 'DockForge <dockforge@gmail.com>'
inputs:
  images:
    description: "Comma-separated list of Docker images to scan"
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true
  output_path:
    description: "Path to store the SBOM files"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Install syft
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Parse image names
      id: parse_images
      shell: bash
      run: |
        IFS=',' read -ra IMAGES <<< "${{ inputs.images }}"
        for image in "${IMAGES[@]}"; do
          echo "IMAGE=$image" >> $GITHUB_ENV
        done

    - name: Create output directory
      shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/${{ inputs.output_path }}

    - name: Scan Docker images with syft
      shell: bash
      run: |
        IFS=',' read -ra IMAGES <<< "${{ inputs.images }}"
        for image in "${IMAGES[@]}"; do
          filename=$(echo $image | tr '/:' '_')
          syft $image --scope all-layers -o syft-table > $GITHUB_WORKSPACE/${{ inputs.output_path }}/packages_$filename.txt
          syft $image --scope all-layers -o json | jq '.' > $GITHUB_WORKSPACE/${{ inputs.output_path }}/sbom_$filename.json
          echo "Created files: $GITHUB_WORKSPACE/${{ inputs.output_path }}/packages_$filename.txt and $GITHUB_WORKSPACE/${{ inputs.output_path }}/sbom_$filename.json"
        done

    - name: List directory for debugging
      shell: bash
      run: |
        ls -la $GITHUB_WORKSPACE/${{ inputs.output_path }}

    - name: Commit and push changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        IFS=',' read -ra IMAGES <<< "${{ inputs.images }}"
        for image in "${IMAGES[@]}"; do
          filename=$(echo $image | tr '/:' '_')
          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/packages_$filename.txt || echo "Failed to add packages_$filename.txt"
          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/sbom_$filename.json || echo "Failed to add sbom_$filename.json"
        done
        git status
        git commit -m "Update SBOM for images: ${{ inputs.images }}."
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD:${{ github.ref }}
branding:
  icon: 'package'
  color: 'red'
