name: 'Docker Package Versions'
description: 'A GitHub Action to capture and list installed packages and their versions in a Docker image.'
author: 'DockForge <dockforge@gmail.com>'
inputs:
  image:
    description: "The Docker image to scan"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      # with:
      #   token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run script inside the target Docker image
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -v /:/host:ro -e GITHUB_ACTOR=${{ github.actor }} ${{ inputs.image }} /bin/bash -c "bash /workspace/src/entrypoint.sh"

    - name: Commit and push changes
      run: |
        cd $GITHUB_WORKSPACE
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add package_versions.txt
        git commit -m "Add package versions report"
        git push
branding:
  color: 'red'
  icon: 'package'
  