name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Docker Package Versions Action
        uses: ./
        with:
          images: "dublok/base-linux:alpine-latest"
          github_token: ${{ secrets.GITHUB_TOKEN }}
